name: Build

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync

      - name: Get metadata
        shell: bash
        run: ./build/metadata.sh "${{ github.ref_name }}" "${{ matrix.os }}" >> "$GITHUB_ENV"

      - name: Build with Nuitka
        shell: bash
        run: uv run nuitka --file-version=${{ env.CLEAN_VERSION }} main.py

      - name: Restructure package
        shell: bash
        run: ./build/restructure.sh

      - name: Package DMG (macOS only)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          mv dist/main.app "dist/${{ github.event.repository.name }}.app"
          brew install create-dmg
          create-dmg \
            --volname "${{ github.event.repository.name }}" \
            --window-pos 200 120 \
            --window-size 500 300 \
            --icon-size 100 \
            --icon "${{ github.event.repository.name }}.app" 150 150 \
            --hide-extension "${{ github.event.repository.name }}.app" \
            --app-drop-link 350 150 \
            "dist/${{ github.event.repository.name }}.dmg" \
            "dist/${{ github.event.repository.name }}.app"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.repository.name }}-${{ env.SHORT_OS }}-${{ github.ref_name }}
          path: ${{ runner.os == 'macOS' && format('dist/{0}.dmg', github.event.repository.name) || 'dist/main.dist/' }}
